DIVS = {
    "ARI": "NL West",
    "ATL": "NL East",
    "BAL": "AL East",
    "BOS": "AL East",
    "CHC": "NL Central",
    "CHW": "AL Central",
    "CIN": "NL Central",
    "CLE": "AL Central",
    "COL": "NL West",
    "DET": "AL Central",
    "MIA": "NL East",
    "HOU": "AL West",
    "KCR": "AL Central",
    "LAD": "NL West",
    "MIL": "NL Central",
    "NYM": "NL East",
    "PHI": "NL East",
    "PIT": "NL Central",
    "SDP": "NL West",
    "SFG": "NL West",
    "STL": "NL Central",
    "WSN": "NL East",
    "LAA": "AL West",
    "MIN": "AL Central",
    "NYY": "AL East",
    "OAK": "AL West",
    "SEA": "AL West",
    "TBR": "AL East",
    "TEX": "AL West",
    "TOR": "AL East",
}
LEAGUE = {team: div.split(" ")[0] for team, div in DIVS.items()}
DIV = {team: div.split(" ")[1] for team, div in DIVS.items()}
