DIVS = {
    "ARI": "NL West",
    "ATL": "NL East",
    "BAL": "AL East",
    "BOS": "AL East",
    "CHC": "NL Central",
    "CHW": "AL Central",
    "CIN": "NL Central",
    "CLE": "AL Central",
    "COL": "NL West",
    "DET": "AL Central",
    "MIA": "NL East",
    "HOU": "AL West",
    "KCR": "AL Central",
    "LAD": "NL West",
    "MIL": "NL Central",
    "NYM": "NL East",
    "PHI": "NL East",
    "PIT": "NL Central",
    "SDP": "NL West",
    "SFG": "NL West",
    "STL": "NL Central",
    "WSN": "NL East",
    "LAA": "AL West",
    "MIN": "AL Central",
    "NYY": "AL East",
    "OAK": "AL West",
    "SEA": "AL West",
    "TBR": "AL East",
    "TEX": "AL West",
    "TOR": "AL East",
}
LEAGUE = {team: div.split(" ")[0] for team, div in DIVS.items()}
DIV = {team: div.split(" ")[1] for team, div in DIVS.items()}

ABBR_TO_NAME = {
    "ARI": "Arizona Diamondbacks",
    "ATL": "Atlanta Braves",
    "BAL": "Baltimore Orioles",
    "BOS": "Boston Red Sox",
    "CHC": "Chicago Cubs",
    "CHW": "Chicago White Sox",
    "CIN": "Cininnati Reds",
    "CLE": "Cleveland Indians",
    "COL": "Colorado Rockies",
    "DET": "Detroit Tigers",
    "MIA": "Miami Marlins",
    "HOU": "Houston Astros",
    "KCR": "Kansas City Royals",
    "LAD": "Los Angeles Dodgers",
    "MIL": "Milwaukee Brewers",
    "NYM": "New York Mets",
    "PHI": "Philadelphia Phillies",
    "PIT": "Pittsburgh Pirates",
    "SDP": "San Diego Padres",
    "SFG": "San Francisco Giants",
    "STL": "St. Louis Cardinals",
    "WSN": "Washington Nationals",
    "LAA": "Los Angeles Angels",
    "MIN": "Minnesota Twins",
    "NYY": "New York Yankees",
    "OAK": "Oakland Athletics",
    "SEA": "Seattle Mariners",
    "TBR": "Tampa Bay Rays",
    "TEX": "Texas Rangers",
    "TOR": "Toronto Blue Jays",
}

NAME_TO_ABBR = {name: abbr for abbr, name in ABBR_TO_NAME.items()}

ABBR_TO_TEAM = {
    "ARI": "Diamondbacks",
    "ATL": "Braves",
    "BAL": "Orioles",
    "BOS": "Red Sox",
    "CHC": "Cubs",
    "CHW": "White Sox",
    "CIN": "Reds",
    "CLE": "Indians",
    "COL": "Rockies",
    "DET": "Tigers",
    "MIA": "Marlins",
    "HOU": "Astros",
    "KCR": "Royals",
    "LAD": "Dodgers",
    "MIL": "Brewers",
    "NYM": "Mets",
    "PHI": "Phillies",
    "PIT": "Pirates",
    "SDP": "Padres",
    "SFG": "Giants",
    "STL": "Cardinals",
    "WSN": "Nationals",
    "LAA": "Angels",
    "MIN": "Twins",
    "NYY": "Yankees",
    "OAK": "Athletics",
    "SEA": "Mariners",
    "TBR": "Rays",
    "TEX": "Rangers",
    "TOR": "Blue Jays",
}

TEAM_TO_ABBR = {team: abbr for abbr, team in ABBR_TO_TEAM.items()}

ABBR_TO_CITY = {
    "ARI": "Arizona",
    "ATL": "Atlanta",
    "BAL": "Baltimore",
    "BOS": "Boston",
    "CHC": "Chicago",
    "CHW": "Chicago",
    "CIN": "Cininnati",
    "CLE": "Cleveland",
    "COL": "Colorado",
    "DET": "Detroit",
    "MIA": "Miami",
    "HOU": "Houston",
    "KCR": "Kansas City",
    "LAD": "Los Angeles",
    "MIL": "Milwaukee",
    "NYM": "New York",
    "PHI": "Philadelphia",
    "PIT": "Pittsburgh",
    "SDP": "San Diego",
    "SFG": "San Francisco",
    "STL": "St. Louis",
    "WSN": "Washington",
    "LAA": "Los Angeles",
    "MIN": "Minnesota",
    "NYY": "New York",
    "OAK": "Oakland",
    "SEA": "Seattle",
    "TBR": "Tampa Bay",
    "TEX": "Texas",
    "TOR": "Toronto",
}

CITY_TO_ABBR = {city: abbr for abbr, city in ABBR_TO_CITY.items()}
